#! /usr/bin/env bash

# reference: https://medium.com/cloud4rpi/diy-home-monitoring-with-raspberrypi-and-cloud4rpi-3b9e6a2ca6ac


# move to a temporary directory

# download the apcups source
wget https://sourceforge.net/projects/apcupsd/files/apcupsd%20-%20Stable/3.14.14/apcupsd-3.14.14.tar.gz
tar xvf apcupsd-3.14.14.tar.gz

# compileand install it
cd apcupsd-3.14.14
./configure --enable-usb
sudo make
sudo make install

# update configurations
#sudo nano /etc/apcupsd/apcupsd.conf
# UPSCABLE usb
#UPSTYPE usb
#DEVICE

#unmask the service
sudo systemctl unmask apcupsd
sudo systemctl enable apcupsd

#start the service
sudo systemctl start apcupsd

